### ISSUE TITLE
Labels not available when creating PR

### ISSUE THREAD

**Issue by daczarne** [joerick/pr-labels-action#7]
I have a workflow that uses `actions/labeler` to set the PR labels. Workflow yaml looks as follows:

```yaml
name: Pull request checks

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  label-pr:
    name: Add PR labels
    runs-on: ubuntu-latest
    steps:
      - name: PR labeler 🏷
        id: add_labels
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  get-pr-labels:
    name: Get the PR labels
    runs-on: ubuntu-latest
    needs: label-pr
    outputs:
      labels: ${{ steps.get_pr_labels.outputs.labels }}
    steps:
      - name: Get PR labels 🏷️
        id: get_pr_labels
        uses: joerick/pr-labels-action@v1.0.6
```

From the `label-pr` we get the following partial log

```txt
##[debug]processing curated-data
##[debug] checking pattern "dags/dmart/curated_data/sql/*.*"
##[debug]  checking "any" patterns
##[debug]    matching patterns against file dags/dmart/curated_data/sql/_dim_product_catalog_updates.sql
##[debug]   - dags/dmart/curated_data/sql/*.*
##[debug]   all patterns matched
##[debug]  "any" patterns matched against dags/dmart/curated_data/sql/_dim_product_catalog_updates.sql
```

which shows that a label was indeed matched. Such label also appears in the PR

![image](https://user-images.githubusercontent.com/16988051/181124338-f967875e-0f7a-4639-8a12-da3b97e76f4b.png)

Yet, the log for `get-pr-labels` shows the following:

![image](https://user-images.githubusercontent.com/16988051/181124439-9b6ccf3b-b2bf-4128-9832-024e4a25703f.png)

No labels were found!

If I re-run all jobs, the same result is observed.

Yet, if any other event occurs, the labels are found. In this case a simple changing of the PR title did the trick (this is because the workflow triggers on PR synchronize).

![image](https://user-images.githubusercontent.com/16988051/181124974-ad3899fb-cef5-4dfa-b884-c0c7645042d6.png)

Not sure how this behaviour could be changed, but it would be nice if the action could detect the labels added during the workflow run in which it is used.

---
This might be quite tricky to achieve since from the `github.event.pull_request` context I can see that, when the PR is opened we get:

```txt
{
  ...
  "event": {
    "action": "opened",
    "pull_request": {
      ...
      "labels": [],
      ...
    }
  ...
}
```
 
But after any other event

```txt
{
  ...
  "event": {
    "action": "synchronize",
    "pull_request": {
      ...
      "labels": [
        {
          "color": "cfd3d7",
          "default": false,
          "description": "dmart",
          "id": 4351199434,
          "name": "dmart",
          "node_id": "LA_kwDOHsmXus8AAAABA1oIyg",
          "url": "https://api.github.com/repos/daczarne/github_actions_test/labels/dmart"
        },
        {
          "color": "7057ff",
          "default": false,
          "description": "Curated data",
          "id": 4351199439,
          "name": "curated-data",
          "node_id": "LA_kwDOHsmXus8AAAABA1oIzw",
          "url": "https://api.github.com/repos/daczarne/github_actions_test/labels/curated-data"
        }
      ],
      ...
    }
  ...
}
```

So it looks as if the labels themselves are out the context at create time.
